before:
  hooks:
    - make clean
    - make deps
    - make gen-ui
    - make build-ui
    - make gen-go
    - make test
release:
  prerelease: auto
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=release
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brew:
  github:
    owner: stratumn
    name: homebrew-groundcontrol
scoop:
  bucket:
    owner: stratumn
    name: groundcontrol-scoop-bucket
  homepage: "https://github.com/stratumn/groundcontrol"
  description: "Application to aid with multi-repository development using a user friendly web interface."
  license: Apache-2.0
