before:
  hooks:
    - make clean
    - make deps
    - make gen-ui
    - make build-ui
    - make gen-go
    - make test
release:
  prerelease: auto
builds:
  - goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=release
archive:
  replacements:
    darwin: macOS
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brew:
  github:
    owner: stratumn
    name: homebrew-groundcontrol
