// Copyright 2019 Stratumn
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//+build ignore

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"
)

func checkError(err error) {
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func main() {
	types := flag.String("t", "", "A comma separated list of types")
	filename := flag.String("o", "", "A filename to output the generated code to")
	flag.Parse()

	w := os.Stdout

	if *filename != "" {
		f, err := os.OpenFile(*filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
		checkError(err)

		defer f.Close()
		defer f.Sync()

		w = f
	}

	t, err := template.New("tmpl").Parse(strings.TrimSpace(tmpl))
	checkError(err)

	err = t.Execute(w, strings.Split(*types, ","))
	checkError(err)
}

var tmpl = `
// Code generated by groundcontrol/scripts/subscriptionsgen.go, DO NOT EDIT.

package resolvers

import (
	"context"
	"encoding/base64"
	"strconv"
	
	"groundcontrol/models"
)

{{range $index, $type := .}}
func (r *subscriptionResolver) {{$type}}Stored(ctx context.Context, id *string, lastMessageID *string) (<-chan *models.{{$type}}, error) {
	ctx = models.WithModelContext(ctx, r.ModelCtx)
	ch := make(chan *models.{{$type}}, SubscriptionChannelSize)

	last := uint64(0)
	if lastMessageID != nil {
		var err error
		last, err = decodeBase64Uint64(*lastMessageID)
		if err != nil {
			return nil, err
		}
	}

	r.ModelCtx.Subs.Subscribe(ctx, models.MessageType{{$type}}Stored, last, func(msg interface{}) {
		nodeID := msg.(string)
		if id != nil && *id != nodeID {
			return
		}
		node := models.MustLoad{{$type}}(ctx, nodeID)
		select {
		case ch <- &node:
		default:
		}
	})

	return ch, nil
}

func (r *subscriptionResolver) {{$type}}Deleted(ctx context.Context, id *string, lastMessageID *string) (<-chan *models.DeletedNode, error) {
	ctx = models.WithModelContext(ctx, r.ModelCtx)
	ch := make(chan *models.DeletedNode, SubscriptionChannelSize)

	last := uint64(0)
	if lastMessageID != nil {
		var err error
		last, err = decodeBase64Uint64(*lastMessageID)
		if err != nil {
			return nil, err
		}
	}

	r.ModelCtx.Subs.Subscribe(ctx, models.MessageType{{$type}}Deleted, last, func(msg interface{}) {
		nodeID := msg.(string)
		if id != nil && *id != nodeID {
			return
		}
		select {
		case ch <- &models.DeletedNode{ID: nodeID}:
		default:
		}
	})

	return ch, nil
}
{{end}}

func decodeBase64Uint64(str string) (uint64, error) {
	data, err := base64.StdEncoding.DecodeString(str)
	if err != nil {
		return 0, err
	}

	return strconv.ParseUint(string(data), 10, 64)
}
`
